Fix checking for windres

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -290,10 +290,10 @@ if test "$ARCH" = "win32"; then
 	if test "x$WINDRES_CHECK" = "x"; then
 		WINDRES="windres"
 		AC_CHECK_PROGS(WINDRES_CHECK, $WINDRES)
-		if test "x$WINDRES_CHECK" = "x"; then
-			echo "*** windres not found";
-			exit 1;
-		fi
+	fi
+	if test "x$WINDRES_CHECK" = "x"; then
+		echo "*** windres not found"
+		exit 1
 	fi
 else
 	WINDRES=""
