changes to support newer libpng (untested)

diff --git a/stratagus/trunk/setup b/stratagus/trunk/setup
--- a/stratagus/trunk/setup
+++ b/stratagus/trunk/setup
@@ -335,21 +335,32 @@ if test "$?" = 0 ; then
     echo " OK";
   fi
 else
-  echo " NOT FOUND!";
-  echo
-  echo "...You do not appear to have a working PNG library installed!"
-  echo
-  echo "libpng is required for freecraft to compile. Please "
-  echo "refer to the LOCAL_PNG section in the setup script to "
-  echo "find out how to install a local copy to compile freecraft."
-  echo
-  echo "Please also note that the PNG library most likely also"
-  echo "requires the GZIP compression library. If you are sure"
-  echo "to have libpng installed, but this test still fails,"
-  echo "check out for libz. You may refer to the LOCAL_ZLIB"
-  echo "section of this script to find out how to install a local"
-  echo "local copy of the libz."
-  echo
+# Newer libpng (1.2.5 up) may need pow() from libm
+  LIBCHECK="$PNG_PATH -lpng $PNG_EXTRA -lm"; check_for_libs
+  if test "$?" = 0 ; then
+    PNG_EXTRA="$PNG_EXTRA -lm"
+    if test "$PNG_LOCAL" = 1 ; then
+      echo " OK (local: $LOCAL_PNG)";
+    else
+      echo " OK";
+    fi
+  else
+    echo " NOT FOUND!";
+    echo
+    echo "...You do not appear to have a working PNG library installed!"
+    echo
+    echo "libpng is required for freecraft to compile. Please "
+    echo "refer to the LOCAL_PNG section in the setup script to "
+    echo "find out how to install a local copy to compile freecraft."
+    echo
+    echo "Please also note that the PNG library most likely also"
+    echo "requires the GZIP compression library. If you are sure"
+    echo "to have libpng installed, but this test still fails,"
+    echo "check out for libz. You may refer to the LOCAL_ZLIB"
+    echo "section of this script to find out how to install a local"
+    echo "local copy of the libz."
+    echo
+  fi
 
   exit 1
 fi
